#!/bin/bash 
USER="melmoth"
PORT="2222"
CWD=$(pwd)
set -e
PDFDIRECTORY=${PDFDIRECTORY:-$CWD/pdf_archive}
a4name=$(basename $1 .xml)_a4.pdf
a4iname=$(basename $1 .xml)_a4_imposed.pdf
lettername=$(basename $1 .xml)_letter.pdf
letteriname=$(basename $1 .xml)_letter_imposed.pdf

echo "The location of pdfs is $PDFDIRECTORY"
targeta4=$PDFDIRECTORY/a4/$a4name
targetletter=$PDFDIRECTORY/letter/$lettername
targeta4i=$PDFDIRECTORY/a4_imposed/$a4iname
targetletteri=$PDFDIRECTORY/letter_imposed/$letteriname
# a4
if [ -f $targeta4 ] ; then 
	scp -P${PORT} $targeta4 ${USER}@theanarchistlibrary.org:/home/melmoth/library/pdfs/a4 
else 
	echo "Error!"
	exit 2
fi 

# letter
if [ -f $targetletter ] ; then 
	scp -P${PORT} $targetletter ${USER}@theanarchistlibrary.org:/home/melmoth/library/pdfs/letter
else 
	echo "Error!"
	exit 2
fi

# a4 imposed
if [ -f $targeta4i ] ; then 
	scp -P${PORT} $targeta4i ${USER}@theanarchistlibrary.org:/home/melmoth/library/pdfs/a4_imposed 
fi 

if [ -f $targetletteri ] ; then 
	scp -P${PORT} $targetletteri ${USER}@theanarchistlibrary.org:/home/melmoth/library/pdfs/letter_imposed
fi

exit 0

